#!/bin/sh

### BEGIN INIT INFO
# Provides:          viewer
# Required-Start:    $remote_fs $syslog $alsa-utils $rsyslog
# Required-Stop:     $remote_fs $syslog $alsa_utils $rsyslog
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

DIR=/home/cubie/viewer
DAEMON=$DIR/viewer.py
DAEMON_NAME=viewer

DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON --chdir $DIR
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
